name: Docker build for every PR
on:
  pull_request:

jobs:
  build_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/Dockerfile
          tags: redturtletech/io-comune-base:develop
          pull: true
          push: false
          cache-from: type=registry,ref=redturtletech/io-comune-base:develop
          cache-to: type=inline
          # platforms: linux/amd64,linux/arm64
          build-args: |
            ADDON_NAME=design-comuni-plone-theme
            ADDON_PATH=design-comuni-plone-theme
            VOLTO_VERSION=17.19.0
