name: Docker build for latest released version
on:
  release:
    types: [released]

jobs:
  build_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/Dockerfile
          tags: redturtletech/io-comune-base:${{ steps.get_version.outputs.VERSION }}
          pull: true
          push: true
          cache-from: type=registry,ref=redturtletech/io-comune-base:${{ steps.get_version.outputs.VERSION }}
          cache-to: type=inline
          build-args: |
            ADDON_NAME=design-comuni-plone-theme
            ADDON_PATH=design-comuni-plone-theme
            VOLTO_VERSION=17.19.0
